# -*- Makefile -*-

# --------------------------------------------------------------------
current_dir := $(dir $(realpath $(lastword $(MAKEFILE_LIST))))

# --------------------------------------------------------------------
JASMINC ?=  /usr/local/bin/jasminc
