name: 'docker'

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:

  check:
    runs-on: [self-hosted, linux, X64, docker]
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: check
        run: make
